### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by yuhei-nishi** [yuhei-nishi/chat-space#10]
# IPアドレス
18.180.121.50

**Comment by yasunamiura** [comment]
西さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①最新メッセージが無いときは自動更新が動かないようにしましょう**
※現在はずっと自動更新が動いている状態です
[![Image from Gyazo](https://i.gyazo.com/5e5b2ade09a6b9c65133f281554763a4.gif)](https://gyazo.com/5e5b2ade09a6b9c65133f281554763a4)

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by yuhei-nishi** [comment]
修正いたしました。
確認お願いします。

**Comment by miyu-yamamoto** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by yuhei-nishi** [comment]
ご確認ありがとうございます。
